'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = {window:{},document:{getElementById(){return null;}}};
vm.runInNewContext(fs.readFileSync(__dirname+'/static/ai.js','utf8'),context);
const config = (values,pets=[])=>JSON.parse(JSON.stringify(context.window.StoneAgeAIInitial.config({elements:{namedItem(name){return {value:String(values[name]??''),checked:Boolean(values[name])};}}},pets)));
assert.deepEqual(config({initial_mode:'birth'}),{mode:'birth',mount:false});
assert.equal(config({initial_mode:'birth',initial_mount:true}).mount,true);
const ridingText=context.window.StoneAgeAIInitial.ridingText;
assert.equal(ridingText({ride_pet_slot:-1}),'未骑乘');
assert.equal(ridingText({ride_pet_slot:0}),'已骑乘第 1 只宠物');
assert.equal(ridingText({}),'待确认');
assert.equal(ridingText({ride_pet_slot:null}),'待确认');
assert.equal(ridingText({ride_pet_slot:5}),'待确认');
const custom={initial_mode:'custom',initial_level:60,initial_hometown:3,initial_vital:1,initial_strength:3,initial_toughness:0,initial_dexterity:0};
assert.equal(config(custom,[{template_id:42,level:30}]).pets[0].level,30);
assert.throws(()=>config(custom,[{template_id:42}]));
assert.equal(config({...custom,initial_mount:true},[{template_id:42,level:30}]).mount,true);
assert.throws(()=>config({...custom,initial_level:'60oops'}));
assert.throws(()=>config({...custom,initial_vital:0,initial_strength:0}));
assert.throws(()=>config({...custom,initial_level:141}));
const random={initial_mode:'random',initial_level_min:10,initial_level_max:60,initial_pet_min:5,initial_pet_max:30,initial_count_min:1,initial_count_max:2};
assert.throws(()=>config(random));
assert.throws(()=>config({...random,initial_level_min:61},[{template_id:42}]));
const generated=config(random,[{template_id:42},{template_id:42},{template_id:43}]);
assert.deepEqual(generated.random.pet_templates,[42,43]);
assert.deepEqual(generated.random.character_level,{min:10,max:60});
assert.equal(generated.mount,false);
assert.equal(config({...random,initial_mount:true},[{template_id:42}]).mount,true);
assert.deepEqual(config({...random,initial_count_min:0,initial_count_max:0}).random.pet_templates,[]);
const source=fs.readFileSync(__dirname+'/static/ai.js','utf8');
assert.match(source,/initialPetLevelField\.hidden = mode !== "custom"/);
assert.match(source,/const custom = value\(form, "initial_mode"\) === "custom"/);
assert.match(source,/\(custom && \(!Number\.isInteger\(level\)/);
assert.match(source,/const mount = checked\(form, "initial_mount"\)/);
assert.match(source,/requestedMount/);
assert.match(source,/ride_pet_slot/);
assert.match(fs.readFileSync(__dirname+'/templates/ai_profiles.html','utf8'),/name="initial_mount"[^>]*checked/);
console.log('admin initial-state configuration tests passed');
