#!/usr/bin/env bash
# Render the Homebrew formula for a released sactl build and push it to the
# tap. Runs locally with an authenticated gh, and in CI with TAP_GITHUB_TOKEN
# (a PAT with contents:write on the tap repository).
#
# Usage:
#   scripts/publish-homebrew-formula.sh <tag>            # publish
#   scripts/publish-homebrew-formula.sh <tag> --dry-run  # print the formula
#
# The tap hosts only the formula; the archives stay on the release page, so
# the release assets must be reachable without authentication.
set -euo pipefail

repo="k0ngk0ng/stoneage"
tap="k0ngk0ng/homebrew-tap"   # tapped as k0ngk0ng/tap
tag="${1:?release tag required, for example v0.1.49}"
mode="${2:-publish}"
version="${tag#v}"

download_sums() {
  local output="$1"
  if [[ -n "${TAP_GITHUB_TOKEN:-}" ]]; then
    GH_TOKEN="$TAP_GITHUB_TOKEN" gh release download "$tag" -R "$repo" -p SHA256SUMS --clobber -O "$output"
  else
    gh release download "$tag" -R "$repo" -p SHA256SUMS --clobber -O "$output"
  fi
}

# The checksums come from the release itself, so the formula cannot drift from
# the published archives.
workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT
download_sums "$workdir/SHA256SUMS"

sum_for() {
  local pattern="$1"
  local value
  value="$(awk -v pattern="$pattern" '$2 ~ pattern {print $1}' "$workdir/SHA256SUMS" | head -1)"
  [[ -n "$value" ]] || { echo "publish-homebrew-formula: no checksum for $pattern in SHA256SUMS" >&2; exit 1; }
  printf '%s' "$value"
}

# Anchor on the archive name: SHA256SUMS also lists the server bundles, and
# an unanchored match silently picks stoneage-assets-sync's hash instead.
arm64_sum="$(sum_for "stoneage-sactl-${tag}-darwin-arm64")"
amd64_sum="$(sum_for "stoneage-sactl-${tag}-darwin-amd64")"

formula="$workdir/sactl.rb"
cat > "$formula" <<EOF
# Generated by scripts/publish-homebrew-formula.sh for ${tag}. Do not edit by
# hand: the next release overwrites this file.
class Sactl < Formula
  desc "Headless StoneAge game client for terminals and agents"
  homepage "https://github.com/${repo}"
  version "${version}"
  on_macos do
    on_arm do
      url "https://github.com/${repo}/releases/download/${tag}/stoneage-sactl-${tag}-darwin-arm64.tar.gz"
      sha256 "${arm64_sum}"
    end
    on_intel do
      url "https://github.com/${repo}/releases/download/${tag}/stoneage-sactl-${tag}-darwin-amd64.tar.gz"
      sha256 "${amd64_sum}"
    end
  end
  on_linux do
    on_arm do
      odie "sactl publishes no linux/arm64 archive yet"
    end
    on_intel do
      url "https://github.com/${repo}/releases/download/${tag}/stoneage-sactl-${tag}-linux-amd64.tar.gz"
      sha256 "$(sum_for "stoneage-sactl-${tag}-linux-amd64")"
    end
  end

  def install
    bin.install "sactl"
  end

  test do
    assert_match "sactl", shell_output("#{bin}/sactl version")
  end
end
EOF

if [[ "$mode" == "--dry-run" ]]; then
  cat "$formula"
  exit 0
fi

# CI authenticates with the PAT; a local run uses the operator's git
# credential helper, which already has access to the tap.
if [[ -n "${TAP_GITHUB_TOKEN:-}" ]]; then
  clone_url="https://x-access-token:${TAP_GITHUB_TOKEN}@github.com/${tap}.git"
else
  clone_url="https://github.com/${tap}.git"
fi

git clone --depth 1 "$clone_url" "$workdir/tap" >/dev/null 2>&1 ||
  { echo "publish-homebrew-formula: cannot clone $tap" >&2; exit 1; }
mkdir -p "$workdir/tap/Formula"
cp "$formula" "$workdir/tap/Formula/sactl.rb"

cd "$workdir/tap"
# Stage first: an untracked file shows no diff, so a fresh tap would be
# mistaken for "already current".
git add Formula/sactl.rb
if git diff --cached --quiet; then
  echo "formula already at ${version}; nothing to publish"
  exit 0
fi
git -c user.name="sactl release" -c user.email="noreply@github.com" \
  commit -q -m "sactl ${version}"
git push -q origin HEAD
echo "published Formula/sactl.rb ${version} to ${tap}"
